# Generated by Django 3.2.18 on 2023-06-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230614_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ccc',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
